// ***************************************
// *                                     *
// *   Created by Elias De Hondt         *
// *   Visit https://eliasdh.com         *
// *                                     *
// ***************************************/
// API Testing

###
// Request to add a new Club without authentication (1)
POST https://localhost:6969/api/Clubs HTTP/1.1
Content-Type: application/json

{
  "name": "Padel club",
  "numberOfCourts": 2,
  "streetName": "Kerkstraat",
  "houseNumber": 1,
  "zipCode": "9000"
}
###
###
// Request to add a new Club as an authenticated user (2)
POST https://localhost:6969/api/Clubs HTTP/1.1
Content-Type: application/json
Cookie: .AspNetCore.Identity.Application=CfDJ8Kir2sV5b8xEqk_koFst_q0k3LYd7LSxYl7OcWyhmP5WxK2kRsqfsS4vhCi043PNEB3yzk_twMAbdJTRyQW0Sqh0J8-5b93fHJ6lLQXlDwsH7aNJyPqjXMWyFjkDl-a1RAgY1i7W25K6kyHnNrrAU9xhPAfloJrSkLNBQqxKjyW4InYKcavNzAbKMXC8B30gpC6bA3pRPYdcC8pR3qV2YCyFd-a0uBx8iFjMaH5SG0SgsO3pw4q05fojkk0DxXwtbXPEkmVV-nP_-MtzXvzC9-eu_Ax-xm9cEkzMM56mBe1szx1AvZ_RZeY-h2mssHK5o3IkImM-bgI3b9f6FZApO2UhyMlr4Px2zNGDxn7JCwoCNjNvkXdkOnCakGxFTwoWZCbwUDNNqRR7ic3ICZdL6YlokVdTKcEps6T4pTeP4TIzIL350-RHzauhziZMk6B9DCuRCfsvIocNdLdSrkKv1HwebwnHc_46bxfFqckeJYOL2R-XPvs23Eqlka_xra7RKGAGPKCzGI6iSzPceK3Z_41gAHtb0RKJijNcT7WR0vpXSFJDYMBzsQU8NaAABCbaSn0y1jelVhtRCDekH9eXM7p2w3p6HKqoQv7yy55N0gkrnL9cla-h-S29ShP6lICDsVowzXauS9NyARy-GzJZP3kshzkT2NTuWV27G_h_d9FZ18732NTi8fNIwXTsWs9ToIGawIHdVNL6cfZNOG8kbiQbh_NV4zvngzHjqWT2dNYhN4sdKCYU0Mtdc6jj4hawWffDlKMDwTm6VNe7YLdGMW1dGJj47ZEyf_bCl1ZPZl75pSDl4qEPrMvW2ts_hF7PfXqUyO6mLDTzpCpT2KTzKg4

{
  "name": "Another Padel Club",
  "numberOfCourts": 3,
  "streetName": "Main Street",
  "houseNumber": 42,
  "zipCode": "1000"
}
###