############################
# @author Elias De Hondt   #
# @see https://eliasdh.com #
# @since 20/03/2024        #
############################

image: mcr.microsoft.com/dotnet/sdk:7.0 # Global image for all jobs

variables:
  OBJECTS_DIRECTORY: 'obj'
  NUGET_PACKAGES_DIRECTORY: '.nuget'
  SOURCE_CODE_PATH: '*/'

cache:
  key: "$CI_COMMIT_REF_SLUG"
  paths:
    - '$SOURCE_CODE_PATH$OBJECTS_DIRECTORY/project.assets.json'
    - '$SOURCE_CODE_PATH$OBJECTS_DIRECTORY/*.csproj.nuget.*'
    - '$NUGET_PACKAGES_DIRECTORY'
  policy: pull-push

before_script:
  - 'dotnet restore --packages $NUGET_PACKAGES_DIRECTORY'

stages:
  - build
  - test
  - deploy

job_build:
  stage: build
  script:
    - 'dotnet build --no-restore'

job_test:
  stage: test
  script:
    - 'dotnet test Tests --logger junit --collect "Xplat Code Coverage"'
  after_script:
    - 'dotnet tool install dotnet-reportgenerator-globaltool --tool-path tools --version 5.2.3'
    - './tools/reportgenerator -reports:"Tests/TestResults/*/coverage.cobertura.xml" -reporttypes:Html -targetdir:"Tests/TestResults/CodeCoverageReport"'
  artifacts:
    when: always
    paths:
      - Tests/TestResults/CodeCoverageReport
    reports:
      junit: Tests/TestResults/TestResults.xml
      coverage_report:
        coverage_format: cobertura
        path: Tests/TestResults/*/coverage.cobertura.xml

job_deploy:
  stage: deploy
  script: echo "Deployment script"
  environment: production