############################
# @author Elias De Hondt   #
# @see https://eliasdh.com #
# @since 20/03/2024        #
############################

image: mcr.microsoft.com/dotnet/sdk:7.0

variables:
  OBJECTS_DIRECTORY: 'obj'
  NUGET_PACKAGES_DIRECTORY: '.nuget'
  SOURCE_CODE_PATH: '*/'

cache:
  key: "$CI_COMMIT_REF_SLUG"
  paths:
    - '$SOURCE_CODE_PATH$OBJECTS_DIRECTORY/project.assets.json'
    - '$SOURCE_CODE_PATH$OBJECTS_DIRECTORY/*.csproj.nuget.*'
    - '$NUGET_PACKAGES_DIRECTORY'
  policy: pull-push

before_script:
  - 'dotnet restore --packages $NUGET_PACKAGES_DIRECTORY'

stages:
  - build
  - test
  - deploy

job_build:
  stage: build
  script:
    - 'dotnet build --no-restore'

job_integration_tests:
  stage: test
  script:
    - 'dotnet test Tests/IntegrationTests --no-restore --collect:"XPlat Code Coverage" --logger junit'
  artifacts:
    when: always
    reports:
      junit: Tests/TestResults/TestResults.xml

job_unit_tests:
  stage: test
  script:
    - 'dotnet test Tests/IntegrationTests --no-restore --collect:"XPlat Code Coverage" --logger junit'
  artifacts:
    when: always
    reports:
      junit: Tests/TestResults/TestResults.xml

job_deploy: # .deploy . is for hidden jobs (This job will not be visible in the pipeline)
  stage: deploy
  script: echo "Deployment script!"
  environment: production