############################
# @author Elias De Hondt   #
# @see https://eliasdh.com #
# @since 01/03/2024        #
############################

# App Engine configuration
env: flex
runtime: custom
service: default

includes:
  - secret.yaml
